USE [CCMS]
GO

/****** Object:  Table [dbo].[Subject]    Script Date: 2/14/2014 11:06:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Subject](
	[SubjectId] [int] NOT NULL,
	[SubName] [varchar](30) NULL,
	[classId] [varchar](20) NULL,
 CONSTRAINT [PK__Subject__AC1BA3A83C69FB99] PRIMARY KEY CLUSTERED 
(
	[SubjectId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Subject]  WITH CHECK ADD  CONSTRAINT [FK__Subject__classId__3E52440B] FOREIGN KEY([classId])
REFERENCES [dbo].[Section] ([SectionId])
GO

ALTER TABLE [dbo].[Subject] CHECK CONSTRAINT [FK__Subject__classId__3E52440B]
GO

